# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Stuff and things
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A place for various bits and bobs that I want to share
author: PurpleCho
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Nav menu pages
header_pages:
  - about.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

#Collections
collections:
  birthday:
    output: true


#Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "birthday" # a collection in your site, in plural form
    values:
      layout: "birthday"
      title: Happy Birthday Autumn!
      hastext: false
      customcss: autumn
      customjs: /assets/toggle.js

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
